# Auto-generated by build_provinces.py. Do not edit manually.
PROVINCES = {
    "Thành phố Cần Thơ": {
        "type": "province",
        "lat": 10.0362046,
        "lon": 105.7872656,
        "code": "15",
        "country": "Việt Nam"
    },
    "Thành phố Huế": {
        "type": "province",
        "lat": 16.4639321,
        "lon": 107.5863388,
        "code": "16",
        "country": "Việt Nam"
    },
    "Thành phố Hà Nội": {
        "type": "province",
        "lat": 21.0283334,
        "lon": 105.854041,
        "code": "11",
        "country": "Việt Nam"
    },
    "Thành phố Hải Phòng": {
        "type": "province",
        "lat": 20.8623278,
        "lon": 106.6799266,
        "code": "14",
        "country": "Việt Nam"
    },
    "Thành phố Hồ Chí Minh": {
        "type": "province",
        "lat": 10.7755254,
        "lon": 106.7021047,
        "code": "12",
        "country": "Việt Nam"
    },
    "Thành phố Đà Nẵng": {
        "type": "province",
        "lat": 16.068,
        "lon": 108.212,
        "code": "13",
        "country": "Việt Nam"
    },
    "Tỉnh An Giang": {
        "type": "province",
        "lat": 10.3188672,
        "lon": 105.0432488,
        "code": "17",
        "country": "Việt Nam"
    },
    "Tỉnh Bắc Ninh": {
        "type": "province",
        "lat": 21.3282166,
        "lon": 106.4625257,
        "code": "18",
        "country": "Việt Nam"
    },
    "Tỉnh Cao Bằng": {
        "type": "province",
        "lat": 22.7426936,
        "lon": 106.1060926,
        "code": "20",
        "country": "Việt Nam"
    },
    "Tỉnh Cà Mau": {
        "type": "province",
        "lat": 9.0180177,
        "lon": 105.0869724,
        "code": "19",
        "country": "Việt Nam"
    },
    "Tỉnh Gia Lai": {
        "type": "province",
        "lat": 14.0201373,
        "lon": 108.6354524,
        "code": "25",
        "country": "Việt Nam"
    },
    "Tỉnh Hà Tĩnh": {
        "type": "province",
        "lat": 18.3504832,
        "lon": 105.7623047,
        "code": "26",
        "country": "Việt Nam"
    },
    "Tỉnh Hưng Yên": {
        "type": "province",
        "lat": 20.6065846,
        "lon": 106.2843471,
        "code": "27",
        "country": "Việt Nam"
    },
    "Tỉnh Khánh Hòa": {
        "type": "province",
        "lat": 12.2980751,
        "lon": 108.9950386,
        "code": "28",
        "country": "Việt Nam"
    },
    "Tỉnh Lai Châu": {
        "type": "province",
        "lat": 22.2921668,
        "lon": 103.1798662,
        "code": "29",
        "country": "Việt Nam"
    },
    "Tỉnh Lào Cai": {
        "type": "province",
        "lat": 22.3069302,
        "lon": 104.1829592,
        "code": "32",
        "country": "Việt Nam"
    },
    "Tỉnh Lâm Đồng": {
        "type": "province",
        "lat": 11.6614957,
        "lon": 108.1335279,
        "code": "30",
        "country": "Việt Nam"
    },
    "Tỉnh Lạng Sơn": {
        "type": "province",
        "lat": 21.8487579,
        "lon": 106.6140692,
        "code": "31",
        "country": "Việt Nam"
    },
    "Tỉnh Nghệ An": {
        "type": "province",
        "lat": 19.1976001,
        "lon": 105.060676,
        "code": "33",
        "country": "Việt Nam"
    },
    "Tỉnh Ninh Bình": {
        "type": "province",
        "lat": 20.2867258,
        "lon": 106.1000359,
        "code": "34",
        "country": "Việt Nam"
    },
    "Tỉnh Phú Thọ": {
        "type": "province",
        "lat": 21.3007538,
        "lon": 105.1349604,
        "code": "35",
        "country": "Việt Nam"
    },
    "Tỉnh Quảng Ngãi": {
        "type": "province",
        "lat": 14.9953739,
        "lon": 108.691729,
        "code": "36",
        "country": "Việt Nam"
    },
    "Tỉnh Quảng Ninh": {
        "type": "province",
        "lat": 21.1718046,
        "lon": 107.2012742,
        "code": "37",
        "country": "Việt Nam"
    },
    "Tỉnh Quảng Trị": {
        "type": "province",
        "lat": 17.2166964,
        "lon": 106.9548246,
        "code": "38",
        "country": "Việt Nam"
    },
    "Tỉnh Sơn La": {
        "type": "province",
        "lat": 21.2276769,
        "lon": 104.1575944,
        "code": "39",
        "country": "Việt Nam"
    },
    "Tỉnh Thanh Hóa": {
        "type": "province",
        "lat": 19.9781573,
        "lon": 105.4816107,
        "code": "42",
        "country": "Việt Nam"
    },
    "Tỉnh Thái Nguyên": {
        "type": "province",
        "lat": 21.9610968,
        "lon": 105.8440789,
        "code": "41",
        "country": "Việt Nam"
    },
    "Tỉnh Tuyên Quang": {
        "type": "province",
        "lat": 22.3382057,
        "lon": 105.0715846,
        "code": "43",
        "country": "Việt Nam"
    },
    "Tỉnh Tây Ninh": {
        "type": "province",
        "lat": 11.0800527,
        "lon": 106.2610531,
        "code": "40",
        "country": "Việt Nam"
    },
    "Tỉnh Vĩnh Long": {
        "type": "province",
        "lat": 10.046765,
        "lon": 106.2947443,
        "code": "44",
        "country": "Việt Nam"
    },
    "Tỉnh Điện Biên": {
        "type": "province",
        "lat": 21.6546566,
        "lon": 103.2168632,
        "code": "22",
        "country": "Việt Nam"
    },
    "Tỉnh Đắk Lắk": {
        "type": "province",
        "lat": 12.8741856,
        "lon": 108.7979302,
        "code": "21",
        "country": "Việt Nam"
    },
    "Tỉnh Đồng Nai": {
        "type": "province",
        "lat": 11.4285446,
        "lon": 107.1624245,
        "code": "23",
        "country": "Việt Nam"
    },
    "Tỉnh Đồng Tháp": {
        "type": "province",
        "lat": 10.425183,
        "lon": 105.9271362,
        "code": "24",
        "country": "Việt Nam"
    }
}